### PR TITLE
fix: refactor API request handling

### LINKED ISSUE #9: Telemetry calls are not using the Horizon URLS
I have it configured to call my local horizon but the telemetry calls are not hitting localhost.
image

### PR DESCRIPTION
**Pull request by chrisllontop**
This fix #9

### CODE REVIEW

File: src/hyphenClient.ts [hunk 1]
```diff
@@ -12,24 +12,25 @@ export class HyphenClient {
...
+  ): Promise<Response> {
     let lastError: unknown;
 
-    for (const url of urls) {
+    for (const baseUrl of this.horizonUrls) {
       try {
-        const response = await this.httpPost(`${url}/toggle/evaluate`, context, logger);
-        return await response.json();
+        const response = await this.httpPost(`${baseUrl}${path}`, payload, logger);
+        return response;
```
Comment (osbornm) [inline src/hyphenClient.ts:33]: Why did we move the JSON out of this func? I think it makes sense to keep the JSON call inside here.

Comment (chrisllontop) [reply src/hyphenClient.ts:33]: @osbornm Basically, the goal is to create a reusable method. Since the telemetry endpoint doesn’t return any data, we can’t use response.json(). For this reason, I moved the JSON call out of this function to make it reusable.  The method `httpPost` validates that `response.ok` is `true` otherwise will throw an error.

Comment (osbornm) [reply src/hyphenClient.ts:33]: Same thing as the server site we should be using the URL class not doing string concatenation.

**Review by osbornm — CHANGES_REQUESTED** [review]

**Review by osbornm — APPROVED** [review]
